### PR TITLE
allow backward compatibility with gcc 4.8

### PR DESCRIPTION
**Pull request by ferdymercury**
Fixes https://github.com/mateidavid/zstr/issues/56
Fixes https://github.com/mateidavid/zstr/issues/59

### CODE REVIEW

**Comment by ferdymercury** [comment]
@behrisch can you test if this solves your issue without having to comment the open function?

**Comment by behrisch** [comment]
Looks good to me, the updated build results will show up tomorrow here: https://build.opensuse.org/package/show/science:dlr/sumo_nightly

**Comment by ferdymercury** [comment]
Do the nightlies work? shall I merge?

**Comment by behrisch** [comment]
yes, please

**Pull request merged**
